function [g,d,v] = def_pap_microcat(mooring, platform, rows, nvars)
% Define global attributes, dimensions, variables and variable attributes
% for a PAP microcat OceanSITES format NetCDF file
% Metadata common to all datatypes set in setup_mooring_pap
% sdate and edate are datenum of the start and end of data to include
% nvars is the number of sensors included
% rows is the number of records included

%% Produce date strings for start and end date and creation date
osite_dfmt = 'yyyy-mm-ddTHH:MM:SSZ';
start_date = datestr(sdate,osite_dfmt);
end_date = datestr(edate,osite_dfmt);
create_date = datestr(now,osite_dfmt);
% Define other codes / strings
data_type = 'CTD'; % data type being written
id = ['OS_' platform '_' datestr(sdate,'yyyymm') '_' data_mode '_' data_type];
dep_str = ['nominal depths of ' int2str(depth) ' metres'];

%%

%% Global Attributes
g = struct(...
  'description', ['File of temperature, conductivity and pressure data collected at '...
                  mooring ' mooring at ', num2str(lat),' Degrees N ' num2str(lon) ' Degrees W'...
                  ' Deployment between ' start_date ' and ' end_date],...
  'summary', ['FixO3 Fixed-point Open Ocean Observatories. '...
             'EU Framework 7 programme (FP7/2007-2013) grant agreement No.312463'],...
  'creation_date',        create_date,...
  'site_code',            mooring,...
  'platform_code',        platform,...
  'data_mode',            'R',...
  'title',                'OceanSITES PAP in-situ data',...
  'naming_authority',     'OceanSITES',...
  'id',                   id,...
  'name',                 id,...
  'source',               'Mooring observation',...
  'principal_investigator', 'Richard Lampitt',...
  'institution',          'NOC',...
  'project',              'FixO3',...
  'network',              'FixO3',...
  'keywords_vocabulary',  'SeaDataNet Parameter Discovery Vocabulary',...
  'keywords',             'WC_Temp, WC_Sal, http://vocab.nerc.ac.uk/collection/P02/current/TEMP/, http://vocab.nerc.ac.uk/collection/P02/current/PSAL/',...
  'comment',              'no comment',...
  'area',                 'North Atlantic Ocean',...
  'geospatial_lat_min',   '48',...
  'geospatial_lat_max',   '50',...
  'geospatial_lat_units', 'degree_north',...
  'geospatial_lon_min',   '-16',...
  'geospatial_lon_max',   '-17',...
  'geospatial_lon_units', 'degree_east',...
  'geospatial_vertical_min', '0',...
  'geospatial_vertical_max', '30',...
  'geospatial_vertical_positive', 'down',...
  'geospatial_vertical_units',    'meter',...
  'time_coverage_start',          start_date,...
  'time_coverage_end',            end_date,...
  'time_coverage_duration',       ['P' num2str(floor(edate-sdate)) 'D'],...
  'time_coverage_resolution',     'PT30M',...
  'cdm_data_type',                'Station',...
  'featureType',                  'timeSeries',...
  'data_type',                    'OceanSITES time-series data',...
  'format_version',               '1.3',...
  'Conventions',                  'CF-1.6',...
  'netcdf_version',               '3.5',...
  'publisher_name',               'Helen Snaith',...
  'publisher_email',              'bodcnocs at bodc.ac.uk',...
  'publisher_url',                'http://www.fixo3.eu',...
  'references',                   'http://www.fixo3.eu, http://www.oceansites.org, http://www.coriolis.eu.org, http://www.eurosites.info',...
  'institution_references',       'http://noc.ac.uk',...
  'data_assembly_center',         'FixO3 DAC',...
  'update_interval',              'void',...
  'license',  ['Follows CLIVAR (Climate Varibility and Predictability) standards, ' ...
                      'cf. http://www.clivar.org/data/data_policy.php. Data available free of charge. '...
                      'User assumes all risk for use of data. User must display citation in any publication or product using data. '...
                      'User must contact PI prior to any commercial use of data.'],...
  'citation', ['These data were collected and made freely available from the PAP-SO '...
                      '(Porcupine Abyssal Plain - Sustained Observatory) and the UK national programs that contribute to it, '...
                      'together with European Projects (FixO3, EuroSITES, MERSEA, ANIMATE) that have supported it, '...
                      'and the OceanSITES project.'],...
  'acknowledgement', ['These data were collected and made freely available from the PAP-SO '...
                      '(Porcupine Abyssal Plain - Sustained Observatory) and the UK national programs that contribute to it, '...
                      'together with European Projects (FixO3, EuroSITES, MERSEA, ANIMATE) that have supported it, '...
                      'and the OceanSITES project.'],...
  'date_created',  create_date,...
  'date_modified', end_date,...
  'history', 'Near real-time processed quality controlled at DAC',...
  'processing_level', 'Instrument data that has been converted to geophysical values',...
  'QC_indicator', 'good_data',...
  'contributor_name', 'http://noc.ac.uk'...
  );

%% Dimensions
d = struct(...
  'DateTime', rows,...
  'Depth', nvars,...
  'Latitude', 1, ...
  'Longitude', 1 ...
  );

%% Variables
v = struct(...
  'DateTime', struct(...
    'xtype',netcdf.getConstant('NC_DOUBLE'),...
    'Atts',struct(...
      'long_name', 'Date and Time',...
      'standard_name', 'time',...
      'description', 'Date and Time from Matlab',...
      'epic_code', int16(601),...
      'units', 'seconds since 1970-01-01 00:00:00',...
      'FillValue',netcdf.getConstant('NC_FILL_DOUBLE'),... % maybe ncfloat(999999)
      'coordinates','lon lat',...
      'axis', 't', ...
      'comments','' ...
      )),...
  'Depth', struct(...
    'xtype',netcdf.getConstant('NC_FLOAT'),...
    'Atts',struct(...
      'long_name', 'Depth of each measurement', ...
      'standard_name', 'depth', ...
      'units', 'meter', ...
      'positive', 'down', ...
      'FillValue', netcdf.getConstant('NC_FILL_FLOAT'),... % ncfloat(99999)
      'valid_min', single(0), ...
      'valid_max', single(12000), ...
      'coordinates', 'lon lat',...
      'axis','z', ...
      'comments','' ...
      )),...
  'Latitude', struct(...
    'xtype',netcdf.getConstant('NC_FLOAT'),...
    'Atts',struct(...
      'long_name', 'latitude of each location', ...
      'standard_name', 'latitude', ...
      'epic_code',  int16(500), ...
      'units', 'degree_north', ...
      'FillValue',netcdf.getConstant('NC_FILL_FLOAT'),... % ncfloat(99999), ...
      'valid_min', single(-90), ...
      'valid_max', single(90), ...
      'comments','' ...
      )), ...
	'Longitude', struct(...
    'xtype',netcdf.getConstant('NC_FLOAT'),...
    'Atts',struct(...
      'long_name', 'longitude of each location', ...
      'standard_name', 'longitude', ...
      'epic_code',  int16(501), ...
      'units',  'degree_west', ...
      'FillValue',netcdf.getConstant('NC_FILL_FLOAT'),... % ncfloat(99999), ...
      'valid_min', single(-180), ...
      'valid_max', single(180), ...
      'comments','' ...
      )), ...
	'TEMP', struct(...
    'xtype',netcdf.getConstant('NC_FLOAT'),...
    'Atts',struct(...
      'long_name', 'Temperature', ...
      'standard_name', 'sea_temperature', ...
      'description', ['Degrees Celcius at ' dep_str], ...
      'epic_code', int16(20), ...
      'units', 'degree_Celsius', ...
      'FillValue', netcdf.getConstant('NC_FILL_FLOAT'),... % ncfloat(99999), ...
      'missing_value',  single(99999), ...
      'valid_min',  single(2.0), ...
      'valid_max',  single(100.0) ...
      )), ...
  'QC_TEMP', struct(...
    'xtype',netcdf.getConstant('NC_INT'),...
    'Atts',struct(...
      'long_name', 'Quality Marker for Temperature', ...
      'description', ['Quality Marker for each ' dep_str], ...
      'FillValue', netcdf.getConstant('NC_FILL_INT'),... % int16(9), ...
      'missing_value', int16(9), ...
      'valid_min', int16(0), ...
      'valid_max', int16(9) ...
      )), ...
	'CNDC', struct(...
    'xtype',netcdf.getConstant('NC_FLOAT'),...
    'Atts',struct(...
      'long_name', 'Conductivity', ...
      'standard_name', 'electrical_conductivity', ...
      'description', ['Conductivity (mS/cm) at ' dep_str], ...
      'epic_code', int16(50), ...
      'units', 'mS/cm', ...
      'FillValue', netcdf.getConstant('NC_FILL_FLOAT'),... % ncfloat(99999), ...
      'missing_value',  single(99999), ...
      'valid_min',  single(25.0), ...
      'valid_max',  single(45.0) ...
      )), ...
	'QC_CNDC', struct(...
    'xtype',netcdf.getConstant('NC_INT'),...
    'Atts',struct(...
      'long_name', 'Quality Marker for Conductivity', ...
      'description', ['Quality Marker for each ' dep_str], ...
      'FillValue', netcdf.getConstant('NC_FILL_INT'),... % int16(9), ...
      'missing_value', int16(9), ...
      'valid_min', int16(0), ...
      'valid_max', int16(9) ...
      )), ...
	'PRES', struct(...
    'xtype',netcdf.getConstant('NC_FLOAT'),...
    'Atts',struct(...
      'long_name', 'PRES', ...
      'standard_name', 'sea_pressure', ...
      'description', ['Pressure (dbar) at ' dep_str], ...
      'epic_code', int16(1), ...
      'units', 'dbar', ...
      'FillValue', netcdf.getConstant('NC_FILL_FLOAT'),... % ncfloat(99999), ...
      'missing_value',  single(99999), ...
      'valid_min',  single(0.0), ...
      'valid_max',  single(12000) ...
      )), ...
	'QC_PRES', struct(...
    'xtype',netcdf.getConstant('NC_INT'),...
    'Atts',struct(...
      'long_name', 'Quality Marker for Pressure', ...
      'description', ['Quality Marker for each ' dep_str], ...
      'FillValue', netcdf.getConstant('NC_FILL_INT'),... % int16(9), ...
      'missing_value', int16(9), ...
      'valid_min',  int16(0), ...
      'valid_max',  int16(9) ...
      )), ...
	'PSAL', struct(...
    'xtype',netcdf.getConstant('NC_FLOAT'),...
    'Atts',struct(...
      'long_name', 'Practical Salinity', ...
      'standard_name', 'practical_salinity', ...
      'description', ['Practical Salinity Units at ' dep_str], ...
      'epic_code', int16(41), ...
      'units', 'PSU', ...
      'FillValue', netcdf.getConstant('NC_FILL_FLOAT'),... % ncfloat(99999), ...
      'missing_value',  single(99999), ...
      'valid_min',  single(29.0), ...
      'valid_max',  single(40.0) ...
      )), ...
	'QC_PSAL', struct(...
    'xtype',netcdf.getConstant('NC_INT'),...
    'Atts',struct(...
      'description', ['Quality Marker for each ' dep_str], ...
      'missing_value', ncint(9), ...
      'FillValue', netcdf.getConstant('NC_FILL_INT'),... % int16(9), ...
      'valid_min',  int16(0), ...
      'valid_max',  int16(9), ...
      'long_name', 'Quality Marker for Practical Salinity' ...
      )) ...
      );
for j=1:nvar;
	if (Wvar(j) < 1)
	nc{['PRES' int2str(v(j))]}.long_name='pressure';
	nc{['PRES' int2str(v(j))]}.standard_name='sea_pressure';
	nc{['PRES' int2str(v(j))]}.units='dbar';
	nc{['PRES' int2str(v(j))]}.FillValue= ncfloat(99999);
	nc{['PRES' int2str(v(j))]}.valid_min= ncfloat(0);
	nc{['PRES' int2str(v(j))]}.valid_max= ncfloat(2000);
	nc{['PRES' int2str(v(j))]}.missing_value= ncfloat(99999);

	nc{['QC_PRES' int2str(v(j))]}=ncint('DateTime','Depthx','Latitude','Longitude');
	nc{['QC_PRES' int2str(v(j))]}.long_name=['Quality Marker for nominal depth of ' int2str(v(j)) ' metres'];
	nc{['QC_PRES' int2str(v(j))]}.units='dbar';
	nc{['QC_PRES' int2str(v(j))]}.FillValue= ncint(9);
	nc{['QC_PRES' int2str(v(j))]}.valid_min= ncint(0);
	nc{['QC_PRES' int2str(v(j))]}.valid_max= ncint(9);
	nc{['QC_PRES' int2str(v(j))]}.missing_value= ncint(9);
	end;
end;
